import Head from 'next/head';

import Navbar from './components/Navbar/Navbar';


export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <p>About</p>
    </>
  );
}