import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

import { ColorMixContext } from '../context/ColorMixContext';

import styles from '../styles/index.module.css';

export default function Home() {
  const [mixed, setMixed] = useState();
  const [right, setRight] = useState();
  const [left, setLeft] = useState();
  const [rightAnimationInProgress, setRightAnimationInProgress] = useState(false);
  const [leftAnimationInProgress, setLeftAnimationInProgress] = useState(false);

  // FIXME: gets rerendered on context change
  // Move Provider to child?
  // https://kentcdodds.com/blog/how-to-optimize-your-context-value

  // TODO: look into if this is needed
  // const providerValue = useMemo(() => ({
  //   right, setRight,
  //   left, setLeft,
  // }), [right, left]);

  return (
    <>
      <Head>
        <title>mint</title>
        <meta name="description" content="colors.wtf mixing and minting app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <ColorMixContext.Provider
        value={{
          mixedContext: [mixed, setMixed],
          leftContext: [left, setLeft],
          rightContext: [right, setRight],
          leftAnimationContext: [leftAnimationInProgress, setLeftAnimationInProgress],
          rightAnimationContext: [rightAnimationInProgress, setRightAnimationInProgress],
        }}
      >
        <div className={styles.homeWrapper}>
          <ColorMix />
          <div className={styles.colorScrollWrapper}>
            <ColorScroll modal={false} />
          </div>
        </div>
      </ColorMixContext.Provider>
    </>
  );
}
