import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Navbar from './components/Navbar/Navbar';
import SwatchGrid from './components/SwatchGrid/SwatchGrid';

const SWATCHES = [
  {
    color: "red",
    name: "Reddy",
    hex: "0xFF0000",
    rgb: "(255, 0, 0)",
    owner: "0x8d1bb337E3291f41ff1434F61D6155bBdE63EE58"
  },
  {
    color: "green",
    name: "greennn",
    hex: "0x00FF00",
    rgb: "(0, 255, 0)",
    owner: "cameron.eth"
  },
  {
    color: "blue",
    name: "blu",
    hex: "0x0000FF",
    rgb: "(0, 0, 255)",
    owner: "cameronmorrongiello.eth"
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SwatchGrid swatches={SWATCHES} />
    </>
  );
}
