import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Navbar from './components/Navbar/Navbar';
import SwatchGrid from './components/SwatchGrid/SwatchGrid';

const SWATCHES = [
  {color: "red"},
  {color: "blue"},
  {color: "green"},
  {color: "white"},
  {color: "red"},
  {color: "blue"},
  {color: "green"},
  {color: "white"},
  {color: "red"},
  {color: "blue"},
  {color: "green"},
  {color: "white"},
  {color: "red"},
  {color: "blue"},
  {color: "green"},
  {color: "white"},
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SwatchGrid swatches={SWATCHES} />
    </>
  );
}
